services:
  db:
    image: postgres:12
    container_name: interface-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=interface
    volumes:
      - app-db:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: interface-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/interface

  frontend:
    build: ./frontend
    container_name: interface-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  app-db: {}